### PR TITLE
Footer links

### PR DESCRIPTION
**Pull request by markymauro13**
Part 1

### CODE REVIEW

**Comment by markymauro13** [comment]
Take a look at line 7, path's not working right in footer for links

**Comment by KennethDoerflein** [comment]
It would be `.` not `..`, if you are going to it from the homepage, which is what we assume as the base case then we use JavaScript to change the path when you are in the other folders such as pages. Also, no need to add `.php` to the path since the server assumes it will be a php file.

**Comment by KennethDoerflein** [comment]
You will need to import the new SQL file into XAMPP to continue working on this. There were conflicts after adding the salary range so I had to merge the main branch into your branch.

**Comment by KennethDoerflein** [comment]
Merging this to make a new branch in the main repo

**Pull request merged**
